name: Testing

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]
        mongodb-version: [4.2]

    steps:
      - uses: actions/checkout@v2

      - name: Start MongoDB v${{ matrix.mongodb-version }}
          uses: supercharge/mongodb-github-action@1.2.0
          with:
            mongodb-version: ${{ matrix.mongodb-version }}

      - name: install
        run: npm ci

      - name: test
        run: |
          npm test
          npm run test:e2e
